# Generated by Django 6.0.2 on 2026-03-06 05:46

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('password', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='Password should be atleast 8 characters with no spaces.', regex='^\\S{8,}$')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.office')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=255)),
                ('transaction', models.CharField(choices=[('simple', 'Simple'), ('complicated', 'Komplikado'), ('technical', 'Lubhang Teknikal')], max_length=12)),
                ('classification_types', multiselectfield.db.fields.MultiSelectField(choices=[('g2b', 'G2B - Government to Business'), ('g2c', 'G2C - Government to Client'), ('g2e', 'G2E - Government to Employee'), ('g2g', 'G2G - Government to Government')], max_length=32)),
                ('availers', models.CharField(max_length=180)),
                ('is_subservice', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.office')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('where_to_secure', models.CharField(max_length=180)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('action', models.CharField(max_length=180)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('legal_basis', models.CharField(max_length=180)),
                ('processing_time', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='StepPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_positions', to='api.position')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_positions', to='api.step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='position',
            field=models.ManyToManyField(through='api.StepPosition', to='api.position'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('name', 'office'), name='unique_name_per_office'),
        ),
    ]
