# Generated by Django 6.0.2 on 2026-03-06 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 6, 16, 35, 29, 717011)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 6, 16, 35, 40, 572379)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stepposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 6, 16, 35, 47, 771900)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
