# Generated by Django 6.0.2 on 2026-03-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requirement_created_at_requirement_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='is_substep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
