# Generated by Django 6.0.2 on 2026-02-04 02:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
