# Generated by Django 6.0.2 on 2026-03-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_number_step_is_substep_step_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='number',
        ),
        migrations.AlterField(
            model_name='service',
            name='number',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
