# Generated by Django 6.0.2 on 2026-03-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_step_number_alter_service_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='is_substep',
            new_name='is_subaction',
        ),
        migrations.AlterField(
            model_name='step',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='step',
            name='legal_basis',
            field=models.CharField(default='None', max_length=180),
        ),
    ]
