# Generated by Django 6.0.2 on 2026-02-24 01:36

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_office_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=255)),
                ('transaction', models.CharField(choices=[('simple', 'Simple'), ('complicated', 'Komplikado'), ('technical', 'Lubhang Teknikal')], max_length=12)),
                ('classification_types', multiselectfield.db.fields.MultiSelectField(choices=[('G2B', 'G2B - Government to Business'), ('G2C', 'G2C - Government to Client'), ('G2E', 'G2E - Government to Employee'), ('G2G', 'G2G - Government to Government')], max_length=32)),
                ('availers', models.CharField(max_length=180)),
                ('is_subservice', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.office')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('where_to_secure', models.CharField(max_length=180)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('action', models.CharField(max_length=180)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('legal_basis', models.CharField(max_length=180)),
                ('processing_time', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.office')),
                ('step', models.ManyToManyField(blank=True, null=True, to='api.step')),
            ],
        ),
    ]
