# Generated by Django 6.0.2 on 2026-02-24 05:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_service_requirement_step_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='classification_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('g2b', 'G2B - Government to Business'), ('g2c', 'G2C - Government to Client'), ('g2e', 'G2E - Government to Employee'), ('g2g', 'G2G - Government to Government')], max_length=32),
        ),
    ]
