# Generated by Django 6.0.2 on 2026-03-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_is_substep_step_is_subaction_alter_step_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='legal_basis',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='processing_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
