# Generated by Django 6.0.2 on 2026-02-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_position_step_step_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.office'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.office'),
        ),
        migrations.AlterField(
            model_name='step',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.office'),
        ),
    ]
