# Generated by Django 6.0.2 on 2026-03-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_disabled',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
