# Generated by Django 6.0.2 on 2026-04-06 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_citizenscharter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenscharter',
            name='charter',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
