# Generated by Django 6.0.2 on 2026-04-06 02:47

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_citizenscharter_charter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenscharter',
            name='charter',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
