# Generated by Django 6.0.2 on 2026-04-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_citizenscharter_charter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenscharter',
            old_name='charter',
            new_name='pdf',
        ),
    ]
