# Generated by Django 6.0.2 on 2026-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_subsector',
            field=models.BooleanField(default=False),
        ),
    ]
