# Generated by Django 6.0.2 on 2026-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sector_is_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='number',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
