# Generated by Django 6.0.2 on 2026-04-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sector_number_alter_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='api.sector'),
            preserve_default=False,
        ),
    ]
