# Generated by Django 6.0.2 on 2026-05-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_office_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenscharter',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charters', to='api.office'),
        ),
    ]
