# Generated by Django 6.0.2 on 2026-05-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_citizenscharter_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitizensCharter',
        ),
    ]
