# Generated by Django 6.0.2 on 2026-05-25 01:32

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_citizenscharter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizensCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('pdf', models.FileField(storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charters', to='api.office')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='api.sector')),
            ],
        ),
    ]
