# Generated by Django 6.0.2 on 2026-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_citizenscharter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='service',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
