# Generated by Django 6.0.2 on 2026-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_sector_number_alter_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
    ]
