# Generated by Django 6.0.2 on 2026-02-04 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_office_created_at_office_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
    ]
