# Generated by Django 6.0.2 on 2026-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_service_classification_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='position',
            field=models.ManyToManyField(to='api.position'),
        ),
    ]
