# Generated by Django 6.0.2 on 2026-03-04 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_position_office_alter_requirement_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(regex='^\\S{8,}$')]),
        ),
    ]
