# Generated by Django 6.0.2 on 2026-03-04 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='Password should be atleast 8 characters with no spaces.', regex='^\\S{8,}$')]),
        ),
    ]
