# Generated by Django 6.0.2 on 2026-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('name', 'office'), name='unique_name_per_office'),
        ),
    ]
