# Generated by Django 6.0.2 on 2026-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_position_unique_name_per_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
