# Generated by Django 6.0.2 on 2026-03-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_step_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='position',
            new_name='position_old',
        ),
    ]
