# Generated by Django 6.0.2 on 2026-03-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_position_step_position_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='position_old',
        ),
        migrations.CreateModel(
            name='StepPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.position')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='position',
            field=models.ManyToManyField(through='api.StepPosition', to='api.position'),
        ),
    ]
