# Generated by Django 6.0.2 on 2026-03-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_step_position_old_stepposition_step_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='position',
        ),
    ]
